export PS1="[\[\e[32m\]\u\[\e[m\]@\[\e[32m\]\h\[\e[m\]] [\w]\n\[\e[35m\]\t\[\e[m\]\\$ "
alias jqc="jq . -C|less -R"
alias ls="ls -haltr"

# Eternal bash history.
# ---------------------
# Undocumented feature which sets the size to "unlimited".
# http://stackoverflow.com/questions/9457233/unlimited-bash-history
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="[%F %T] "

# Add brew python to path
export PATH="/home/alex/bin:/home/alex/.local/bin:/usr/local/opt/python/libexec/bin:/opt/packer:$PATH"

# Ignore commands that start with a space
export HISTIGNORE=' *'

# Set location of ansible vault password file
export ANSIBLE_VAULT_PASSWORD_FILE=~/.vault_pass.txt

# Change the file location because certain bash sessions truncate .bash_history file upon close.
# http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
export HISTFILE=~/.bash_eternal_history

# Force prompt to write history after every command.
# http://superuser.com/questions/20900/bash-history-loss
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

export JENKINS_API_USER="alex"
export JENKINS_API_TOKEN="$(cat ~/.ssh/jenkins_api_token)"
export VCENTER_USERNAME="$(cat ~/.ssh/vcenter_username)"
export VCENTER_PASSWORD="$(cat ~/.ssh/vcenter_password)"
export GOVC_USERNAME="${VCENTER_USERNAME}"
export GOVC_PASSWORD="${VCENTER_PASSWORD}"
export GOVC_URL=""
export GOVC_INSECURE=true
