---
- name: "Install ansible with pip"
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - ansible

- name: "Install needed python libraries"
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - jenkinsapi
    - pyvmomi
