---
#- name: "Install ansible with pip"
#  pip:
#    name: ansible
#    state: present
#    version: "{{ target_ansible_version }}"
#  when: ansible_connection != "local"

- name: "Install needed python libraries"
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
  with_items:
    - { name: "jenkinsapi", version: "0.3.6" }
    - { name: "pyvmomi", version: "6.7.0" }
    - { name: "openshift", version: "0.5.0" }
    - { name: "pyyaml", version: "3.12" }
