- hosts: local-workstation
  gather_facts: true
  tasks:
    - import_role:
        name: "{{ item }}"
      when: ansible_distribution == Ubuntu
      with_items:
      - environment

    - import_role:
        name: "{{ item }}"
      when: ansible_distribution == MacOSX
      with_items:
      - docker
      - environment
      - git
      - haskell
      - kubernetes
      - osx-software
      - packer-etc
      - puppet-tools
      - python
      - ubuntu-gui-software
      - ubuntu-terminal-utilities
      - vmware-fusion
      vars:
        ansible_connection: local
