- hosts: provisioner
  gather_facts: true
  become: true
  vars:
    ansible_connection: local
  tasks:
    - include_role:
        name: environment
        apply:
          become: false
      when: ansible_distribution == 'Ubuntu'

    - include_role:
        name: "{{ item }}"
      when: ansible_distribution == 'Ubuntu'
      loop:
      - git
      - ubuntu-terminal-utilities
      - docker
      - packer-etc
      #- ansible
      #- ubuntu-terminal-utilities

    - include_role:
        name: "{{ item }}"
      when: ansible_distribution == 'MacOSX'
      loop:
      - docker
      - environment
      - git
      - haskell
      - kubernetes
      - osx-software
      - packer-etc
      - puppet-tools
      - python
      - ubuntu-gui-software
      - vmware-fusion
