- hosts: provisioner
  gather_facts: true
  become: true
  vars:
    ansible_connection: local
  tasks:
    - include_role:
        name: "{{ item }}"
      when: ansible_distribution == 'Ubuntu'
      with_items:
      - environment
      - git
      - ubuntu-terminal-utilities
      - packer-etc

    - include_role:
        name: "{{ item }}"
      when: ansible_distribution == 'MacOSX'
      with_items:
      - docker
      - environment
      - git
      - haskell
      - kubernetes
      - osx-software
      - packer-etc
      - puppet-tools
      - python
      - ubuntu-gui-software
      #- ubuntu-terminal-utilities
      - vmware-fusion
