---
- name: "create directories"
  file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ initiating_user }}"
  with_items:
  - "/home/{{ initiating_user }}/.vim/backup"
  - "/home/{{ initiating_user }}/.vim/swap"
  - "/home/{{ initiating_user }}/workspace"

- name: "install ansible config file"
  copy:
    src: ansible.cfg
    dest: "/home/{{ initiating_user }}/.ansible.cfg"
    owner: "{{ initiating_user }}"

- name: "install secondary bashrc"
  copy:
    src: bashrc
    dest: "/home/{{ initiating_user }}/.bashrc-{{ initiating_user }}"
    mode: 0755
    owner: "{{ initiating_user }}"

- name: "link secondary bashrc to the main"
  lineinfile:
    line: "[[ -r /home/{{ initiating_user }}/.bashrc-{{ initiating_user }} ]] && source /home/{{ initiating_user }}/.bashrc-{{ initiating_user }}"
    insertafter: EOF
    path: "/home/{{ initiating_user }}/.bash_profile"
    create: yes
    state: present
    owner: "{{ initiating_user }}"
    mode: 0755

- name: "install the user's .vimrc"
  copy:
    src: vimrc
    dest: "/home/{{ initiating_user }}/.vimrc"
    owner: "{{ initiating_user }}"
    mode: 0644
