---
- name: "create directories"
  file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
  with_items:
  - "{{ ansible_env.HOME }}/.vim/backup"
  - "{{ ansible_env.HOME }}/.vim/swap"
  - "{{ ansible_env.HOME }}/workspace"

- name: "install ansible config file"
  copy:
    src: ansible.cfg
    dest: "{{ ansible_env.HOME }}/.ansible.cfg"
    owner: "{{ ansible_user_id }}"

- name: "install secondary bashrc"
  copy:
    src: bashrc
    dest: "{{ ansible_env.HOME }}/.bashrc-{{ ansible_user_id }}"
    mode: 0755
    owner: "{{ ansible_user_id }}"

- name: "link secondary bashrc to the main"
  lineinfile:
    line: "[[ -r ~/.bashrc-{{ ansible_user_id }} ]] && source ~/.bashrc-{{ ansible_user_id }}"
    insertafter: EOF
    path: "{{ ansible_env.HOME }}/.bash_profile"
    create: yes
    state: present
    owner: "{{ ansible_user_id }}"
    mode: 0755

- name: "install the user's .vimrc"
  copy:
    src: vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
    owner: "{{ ansible_user_id }}"
    mode: 0644
